name: example
description: TIKI SDK Dart Example app.
version: 1.0.0
publish: none
homepage: https://mytiki.com

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  pointycastle: ^3.7.3
  sqlite3: ^1.11.2
  http: ^1.0.0
  html: ^0.15.3
  uuid: ^3.0.7
  tiki_sdk_dart: 
    path: ../.

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.3
