name: example
description: TIKI SDK Dart Example app.
version: 1.0.0
publish: none
homepage: https://mytiki.com

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  pointycastle: ^3.7.2
  sqlite3: ^1.10.1
  http: ^0.13.5
  html: ^0.15.2
  uuid: ^3.0.7
  tiki_sdk_dart: 
    path: ../.

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
