name: tiki_sdk_dart
description: The core implementation (pure dart) of TIKI's decentralized infrastructure plus abstractions to simplify the tokenization and application of data ownership, consent, and rewards. For new projects, we recommend one of our platform-specific SDKs. Same features. Much easier to implement.
version: 0.0.14
homepage: https://mytiki.com
documentation: https://docs.mytiki.com
repository: https://github.com/tiki/tiki-sdk-dart
issue_tracker: https://github.com/tiki/tiki-sdk-dart/issues

environment:
  sdk: ">=2.17.0 <3.0.0"
  
dependencies:
  pointycastle: ^3.6.1
  sqlite3: ^1.7.2
  http: ^0.13.5
  html: ^0.15.0
  uuid: ^3.0.6

dev_dependencies:
  test: ^1.21.4
  flutter_lints: ^2.0.1


