name: tiki_sdk_dart
description: TIKI SDK - Dart
version: 0.0.1
homepage: https://github.com/tiki/tiki-sdk-dart

environment:
  sdk: ">=2.17.0 <3.0.0"

dev_dependencies:
  test: ^1.21.4
  flutter_lints: ^2.0.1

