name: tiki_sdk_dart
description: Create and enforce immutable data licensing records client-side. The core-implementation of TIKI's client-side infrastructure.
version: 2.1.2
homepage: https://mytiki.com
documentation: https://docs.mytiki.com/docs/sdk-overview
repository: https://github.com/tiki/tiki-sdk-dart
issue_tracker: https://github.com/tiki/tiki-sdk-dart/issues

environment:
  sdk: ">=2.17.0 <3.0.0"
  
dependencies:
  pointycastle: ^3.7.2
  sqlite3: ^1.10.1
  http: ^0.13.5
  html: ^0.15.2
  uuid: ^3.0.7
  nock: ^1.2.1

dev_dependencies:
  test: ^1.24.0
  flutter_lints: ^2.0.1
  build_web_compilers: ^3.2.7
  build_runner: ">=1.6.2 <3.0.0"


