name: tiki_sdk_dart
description: Create and enforce immutable data licensing records client-side. The core-implementation of TIKI's client-side infrastructure.
version: 3.0.0
homepage: https://mytiki.com
documentation: https://docs.mytiki.com/docs/sdk-overview
repository: https://github.com/tiki/tiki-sdk-dart
issue_tracker: https://github.com/tiki/tiki-sdk-dart/issues

environment:
  sdk: ">=2.17.0 <3.0.0"
  
dependencies:
  pointycastle: ^3.7.3
  sqlite3: ^1.11.2
  http: ^1.0.0
  html: ^0.15.3
  uuid: ^3.0.7

dev_dependencies:
  test: ^1.24.3
  flutter_lints: ^2.0.1
  build_web_compilers: ^4.0.3
  nock: ^1.2.2
  build_runner: ">=1.6.2 <3.0.0"


