name: Release

on:
  pull_request:
    branches:
      - main
    types:
      - closed

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  release:
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/')
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: 'main'

      - name: 'Setup Dart'
        uses: dart-lang/setup-dart@v1.3
        with:
          sdk: 2.18.2

      - name: 'Setup credentials'
        run: |
          mkdir $XDG_CONFIG_HOME/dart
          echo '${{ secrets.PUB_DEV_CREDENTIALS }}' > "$XDG_CONFIG_HOME/dart/pub-credentials.json"

      - name: Run tests
        run: dart test

      - name: Git version
        id: version
        uses: codacy/git-version@2.7.1
        with:
          release-branch: "main"
          minor-identifier: "feat"

      - name: Create a new tag
        run: |
          git tag ${{ steps.version.outputs.version }}
          git push origin ${{ steps.version.outputs.version }}

      - name: 'Publish'
        run: dart pub publish -f

      - name: Create a Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{steps.version.outputs.version }}

  docs:
    runs-on: ubuntu-latest
    needs: [ release ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.1

      - name: Guide
        uses: readmeio/rdme@8.3.0
        with:
          rdme: docs doc/guide --key=${{ secrets.README_API_KEY }}

      - name: Ref
        uses: readmeio/rdme@8.3.0
        with:
          rdme: docs doc/ref --key=${{ secrets.README_API_KEY }}

      - name: Release
        uses: softprops/action-gh-release@v1