name: Tests

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: dart-lang/setup-dart@v1.3

      - name: Install dependencies
        run: dart pub get

      - name: Run tests
        run: dart test --reporter github

      - name: Static code analysis
        run: |
          cd lib
          dart format . -o show --set-exit-if-changed

      - name: Check dart publish
        run: dart pub publish --dry-run