name: Version

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  bump:
    if: startsWith(github.head_ref, 'release/')
    environment: Production
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.semver.outputs.nextStrict }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1.3
          
      - name: Get Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: main

      - name: Set Version
        run: |
          sed -i 's/version:*.*.*/version: ${{ steps.semver.outputs.nextStrict }}/' pubspec.yaml

      - name: Commit Changes
        run: |
          git add pubspec.yaml
          git commit -m 'version bump'
          git push